### ISSUE TITLE
Problems with Laravel 5.4

### ISSUE THREAD

**Issue by vanushwashere** [chefsplate/laravel-mongodb-queue#1]
Hi :)
My server is running Laravel 5.4 on PHP7 apache with mongodb v.3.4.3.
Today I've faced an issue using this package as queue driver.
It was giving me an "property $expire not exist in MongoDBQueue.php on line 89" error.
I know that in readme file there is no information about 5.4 support, but I found composer file changes for 5.4 version in latest commits.

Now I downgraded Laravel to 5.3 just to use your package, and I have a question: will 5.4 version be released in near future?

**Comment by davidchchang** [comment]
Hey @vanushwashere, thanks for your issue report! We haven't upgraded to 5.4 yet, but will do so in the near future. We'll definitely be upgrading this package when the time comes (expected within the next month or two). Thanks again for your bug report, and will keep you posted!

**Comment by vanushwashere** [comment]
#2 Here I made some changes, take a look on them

**Comment by vanushwashere** [comment]
@davidchchang how it's going ?

**Comment by adrisonluz** [comment]
@davidchchang please, merge the adjustments he made.

**Comment by davidchchang** [comment]
Terribly sorry for the delay. I have not had much time to work on this for a while. I'll merge the changes right now.

Will do my best to carve out more time to update these packages to support the latest versions of Laravel in the near future.

**Comment by davidchchang** [comment]
We are aware of the timeout issue and will address. Thanks for reporting.

**Comment by davidchchang** [comment]
Changes merged into `master` and `5.4`

**Comment by adrisonluz** [comment]
Tks bro!
